### ISSUE TITLE
Rekusionsverfahren Form

### ISSUE THREAD

**Issue by Erase01** [Erase01/program-collection#1]
- [x] Form design finished
- [x] Base code complete

### TODO:
- [x] fix infinite loop

### Extra Features:

- History of the results calculated
