### ISSUE TITLE
Method Form

### ISSUE THREAD

**Issue by Erase01** [Erase01/program-collection#3]
- [x] Design Form
- [x] Void Method
- [x] Return Method
- [x] Ref Method
---
- [x] Draw Forms (Rectangle) on panel

### ToDo:
- [x] Draw rhombus, trapezoid, triangle and circle on panel
- Clean up script and form

### Extra Features:
- [x] large shapes adjustable with sizebar (for method with return)
